Pro.Mvc/Controllers/CommonController.cs
using Pro.Data.Entities;
using Pro.Mvc.Models;
using Nistec.Data.Entities;
using Nistec.Generic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Pro.Lib;
using Nistec;
using Nistec.Serialization;
using Pro.Data.Entities.Props;
using PropsEnum=Pro.Data.Entities.PropsEnum;
using Nistec.Data;
using Pro.Data;
using Nistec.Web.Security;
using Pro.Lib.Query;
using Nistec.Web.Controls;


namespace Pro.Mvc.Controllers
{
    [Authorize]
    public class CommonController : BaseController
    {

        [HttpGet]
        public ActionResult Dashboard()
        {
            return View(true);
        }

        #region Lookups

        [HttpPost]
        public JsonResult Lookup_Autocomplete(string type, string search)
        {
            int accountId = GetAccountId();
            var list = DbLookups.Autocomplete(accountId, type, search);
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Lookup_DisplayList(string type)
        {
            int accountId = GetAccountId();
            var list = DbLookups.DisplayList(accountId, type);
            return Json(list, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult Lookup_GetList(string type)
        {
            int accountId = GetAccountId();

            switch (type)
            {
                case "members":
                    return Json(DbLookups.ViewEntityList(EntityGroups.Enums, "BranchId", "BranchName", "lu_Members", accountId), JsonRequestBehavior.AllowGet);
                case "branch":
                    return Json(DbLookups.ViewEntityList(EntityGroups.Enums, "BranchId", "BranchName", "Branch", accountId), JsonRequestBehavior.AllowGet);
                case "charge":
                    return Json(DbLookups.ViewEntityList(EntityGroups.Enums, "ChargeId", "ChargeName", "Charge", accountId), JsonRequestBehavior.AllowGet);
                case "city":
                    return Json(DbLookups.ViewEntityList(EntityGroups.Enums, "CityId", "CityName", "Cities", accountId), JsonRequestBehavior.AllowGet);
                //case "place":
                //    return Json(EntityLibPro.ViewEntityList<PlaceView>(EntityGroups.Enums, PlaceView.TableName, accountId), JsonRequestBehavior.AllowGet);
                case "region":
                    return Json(DbLookups.ViewEntityList(EntityGroups.Enums, "RegionId", "RegionName", "Region", accountId), JsonRequestBehavior.AllowGet);
                case "category":
                    return Json(DbLookups.ViewEntityList(EntityGroups.Enums, "CategoryId", "CategoryName", "Categories", accountId), JsonRequestBehavior.AllowGet);
                case "role":
                    return Json(DbLookups.ViewEntityList(EntityGroups.Enums, "RoleId", "RoleName", "Roles", accountId), JsonRequestBehavior.AllowGet);
                case "status":
                    return Json(DbLookups.ViewEntityList(EntityGroups.Enums, "StatusId", "StatusName", "Status", accountId), JsonRequestBehavior.AllowGet);
                case "enum1":
                case "exenum1":
                    return Json(DbLookups.ViewEnumList(EntityGroups.Enums, "PropId", "PropName", "Enum", accountId, 1), JsonRequestBehavior.AllowGet);
                case "enum2":
                case "exenum2":
                    return Json(DbLookups.ViewEnumList(EntityGroups.Enums, "PropId", "PropName", "Enum", accountId, 1), JsonRequestBehavior.AllowGet);
                case "enum3":
                case "exenum3":
                    return Json(DbLookups.ViewEnumList(EntityGroups.Enums, "PropId", "PropName", "Enum", accountId, 1), JsonRequestBehavior.AllowGet);
                default:
                    return Json(DbLookups.ViewEntityList(EntityGroups.Enums, "Value", "Label", type, accountId), JsonRequestBehavior.AllowGet);

                    //return Json(null, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult Lookup_EnumList(int type)
        {
            int accountId = GetAccountId();
            return Json(DbLookups.ViewEnumList(accountId, type), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Lookup_MemberDisplay(int id)
        {
            int accountId = GetAccountId();
            var value = DbLookups.Member_Display("DisplayName", "AccountId", accountId, "RecordId", id);
            return Json(value);// ContentModel.Get(value), JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult Lookup_UserDisplay(int id)
        {
            int accountId = GetAccountId();
            var value = DbLookups.UserProfile("DisplayName", "AccountId", accountId, "UserId", id);
            return Json(value);// ContentModel.Get(value), JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Common Properties

        [HttpPost]
        public JsonResult DefEntityView(string entity)
        {
            int accountId = GetAccountId();

            switch (entity)
            {
                case "branch":
                    return Json(EntityLibPro.ViewEntityList<BranchView>(EntityGroups.Enums, BranchView.TableName, accountId), JsonRequestBehavior.AllowGet);
                case "charge":
                    return Json(EntityLibPro.ViewEntityList<ChargeView>(EntityGroups.Enums, ChargeView.TableName, accountId), JsonRequestBehavior.AllowGet);
                case "city":
                    return Json(EntityLibPro.ViewEntityList<CityView>(EntityGroups.Enums, CityView.TableName, 0), JsonRequestBehavior.AllowGet);
                //case "place":
                //    return Json(EntityLibPro.ViewEntityList<PlaceView>(EntityGroups.Enums, PlaceView.TableName, accountId), JsonRequestBehavior.AllowGet);
                case "region":
                    return Json(EntityLibPro.ViewEntityList<RegionView>(EntityGroups.Enums, RegionView.TableName, 0), JsonRequestBehavior.AllowGet);
                case "category":
                    return Json(EntityLibPro.ViewEntityList<CategoryView>(EntityGroups.Enums, CategoryView.TableName, accountId), JsonRequestBehavior.AllowGet);
                case "role":
                    return Json(EntityLibPro.ViewEntityList<RoleView>(EntityGroups.Enums, RoleView.TableName, accountId), JsonRequestBehavior.AllowGet);
                case "status":
                    return Json(EntityLibPro.ViewEntityList<StatusView>(EntityGroups.Enums, StatusView.TableName, accountId), JsonRequestBehavior.AllowGet);
                case "enum1":
                case "exenum1":
                    return Json(EntityLibPro.ViewEntityList<EnumView>(EntityGroups.Enums, EnumView.TableName, accountId,1), JsonRequestBehavior.AllowGet);
                case "enum2":
                case "exenum2":
                    return Json(EntityLibPro.ViewEntityList<EnumView>(EntityGroups.Enums, EnumView.TableName, accountId,2), JsonRequestBehavior.AllowGet);
                case "enum3":
                case "exenum3":
                    return Json(EntityLibPro.ViewEntityList<EnumView>(EntityGroups.Enums, EnumView.TableName, accountId,3), JsonRequestBehavior.AllowGet);
                default:
                    return Json(null, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult DefEntityEnumView(string entity)
        {
            int accountId = GetAccountId();

            switch (entity)
            {
                case "status":
                    return Json(PropsEnum.EntityEnum.ViewEntityList<PropsEnum.StatusView>(PropsEnum.StatusView.TableName, "Status", accountId), JsonRequestBehavior.AllowGet);
                //case "category":
                //    return Json(EntityEnum.ViewEntityList<CategoryView>(CategoryView.TableName, "Category", accountId), JsonRequestBehavior.AllowGet);
                //case "region":
                //    return Json(EntityEnum.ViewEntityList<RegionView>(RegionView.TableName, "Region", accountId), JsonRequestBehavior.AllowGet);
                case "role":
                    return Json(PropsEnum.EntityEnum.ViewEntityList<PropsEnum.RoleView>(PropsEnum.RoleView.TableName, "Role", accountId), JsonRequestBehavior.AllowGet);
                default:
                    return Json(null, JsonRequestBehavior.AllowGet);
            }
        }

        #endregion

        #region Def
         [HttpGet]
        public ActionResult DefCity()
        {
            return View(true);
        }

        [HttpPost]
        public JsonResult DefCityDelete(int PropId)
        {
            //ValidateAdmin();
            int result = 0;
            ResultModel rm = null;
            int accountId = GetAccountId();
            try
            {
                result = CityView.DoDelete(PropId, accountId);
                rm = new ResultModel(result);
            }
            catch (Exception ex)
            {
                string err = ex.Message;
                result = -1;
                rm = new ResultModel()
                {
                    Status = result,
                    Message = err
                };
            }
            return Json(rm, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult DefCityUpdate(int PropId, string PropName, int RegionId, int command)
        {
            //ValidateAdmin();
            int result = 0;
            ResultModel rm = null;
            int accountId = GetAccountId();
            try
            {
                result = CityView.DoSave(PropId, PropName, RegionId, accountId, (UpdateCommandType)command);
                rm = new ResultModel(result);
            }
            catch (Exception ex)
            {
                string err = ex.Message;
                result = -1;
                rm = new ResultModel()
                {
                    Status = result,

Pro.Mvc/Views/Common/DefCity.cshtml
@{
    Layout = "~/Views/Shared/_ViewCo.cshtml";
    Page.Title = "Main";
    var userInfo = @Html.Raw(Json.Encode(ViewBag.UserInfo));
}
@section head {
    @Scripts.Render("~/bundles/jqx")

    @Scripts.Render("~/bundles/jqxgrid")
    <script type="text/javascript" src="~/Scripts/app/model/generic/_baseEntity-def.js"></script>
    <script type="text/javascript" src="~/Scripts/app/model/generic/city-def.js"></script>
    <script type="text/javascript" src="~/Scripts/app/app-jqx-grid-1.0.js?ver=20180001"></script>
    <style type="text/css">
        .input {
            direction: rtl;
            text-align: right;
            height: 24px;
        }
    </style>
}
@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            var theme = 'Arctic';
            JSON.useDateParser();
            var def = new app_city_def(JSON.parse('@userInfo'));

        });
    </script>
}
<div class="breadcrumbs">
</div>
<div class="global-view">
    <div class="container-box">

        <div class="grid-wrap rtl panel-area">
            <h3 class="rtl panel-area-title">הגדרות כלליות-<span>ערים-אזורים</span></h3>
            <div id="jqxWidget" style="max-width: 500px;">
                <!--<input style="margin-right: 5px;" type="button" id="addrowbutton" value="הוספה" />-->
                <div id="jqxgrid" style="position:relative;z-index:1;"></div>

                <div style="font-size: 12px; font-family: Verdana, Geneva, 'DejaVu Sans', sans-serif; margin-top: 30px;">
                    <div class="note-edit">לעריכת שורה: לחיצה כפולה על השורה הרצויה</div>

                    <div id="popupWindow">
                        
                        <div>עריכה</div>
                        <div style="overflow: hidden;direction:rtl">
                            <input type="hidden" id="insertFlag" value="0" />
                                <form id="form" action="./">
                                <table style="border-spacing: 10px;border-collapse: separate;direction:rtl">
                                    <tr id="trcode">
                                        <td align="right">קוד עיר:</td>
                                        <td align="left"><input id="PropId" readonly="readonly" class="input" /></td>
                                    </tr>
                                    <tr>
                                        <td align="right">שם עיר:</td>
                                        <td align="left"><input id="PropName" class="input" /></td>
                                    </tr>
                                    <tr>
                                        <td align="right">אזור:</td>
                                        <td align="left"><div id="RegionId" name="RegionId"></div></td>
                                    </tr>
                                    <tr>
                                        <td align="right"></td>
                                        <td style="padding-top: 10px;" align="right">
                                            <input style="margin-right: 5px;" type="button" id="Save" value="עדכון" />
                                            <input id="Cancel" type="button" value="ביטול" />
                                        </td>
                                    </tr>
                                </table>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    app_menu.activeLayoutMenu("liEntity");
    app_menu.breadcrumbs("Main", "DefCity", 'en');
</script>

Pro.Mvc/Views/Common/DefEntity.cshtml
@{
    Layout = "~/Views/Shared/_ViewCo.cshtml";
    Page.Title = "Main";
    //string entity = Request["entity"];
    //string TagPropId = ViewBag.TagPropId;
    //string TagPropName = ViewBag.TagPropName;
    //string TagPropTitle = ViewBag.TagPropTitle;
    var userInfo = @Html.Raw(Json.Encode(ViewBag.UserInfo));
}
@section head {
    @Scripts.Render("~/bundles/jqx")
    @Scripts.Render("~/bundles/jqxgrid")
    @*<script type="text/javascript" src="~/Scripts/app/model/generic/_baseEntity-def.js"></script>*@
    <script type="text/javascript" src="~/Scripts/app/model/generic/entity-def.js"></script>
    <script type="text/javascript" src="~/Scripts/app/app-jqx-grid-1.0.js"></script>
    <style type="text/css">
        .input {
            direction: rtl;
            text-align: right;
            height: 24px;
        }
    </style>
}
@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            var theme = 'Arctic';
            JSON.useDateParser();

            var def;
            app_jqx_list.entityEnumComboAdapter();
            $("#EntityEnumType").on('change', function () {
                var item = $("#EntityEnumType").jqxDropDownList('getSelectedItem');
                var entityType = item.value;
                var tagPropTitle = item.label;
                if (def == null || def === undefined) {
                    def = new app_entity_def(JSON.parse('@userInfo'), entityType, tagPropTitle);
                }
                else {
                    def.loadEntity(entityType, tagPropTitle);
                    def.reloadData(def);
                }
            });
            $("#EntityEnumType").jqxDropDownList({ selectedIndex: 0 });
        });

    </script>
}
<div class="breadcrumbs">
</div>
<div class="global-view">
    <div class="container-box">

        <div class="grid-wrap rtl panel-area">
            <h3 class="rtl panel-area-title">הגדרות כלליות-<span id="tagPropTitle">סניף</span></h3>
            <div id="EntityEnumType"></div>
            <div id="jqxWidget" style="max-width:500px">
                <div id="jqxgrid" style="position: relative; z-index: 1;"></div>
                <div class="note-edit">לעריכת שורה: לחיצה כפולה על השורה הרצויה</div>

                <div style="margin-top: 30px;">
                    <div id="cellbegineditevent"></div>
                    <div style="margin-top: 10px;" id="cellendeditevent"></div>
                    <div id="popupWindow">
                        
                        <div>עריכה</div>
                        <div style="overflow: hidden; direction: rtl">
                            <input type="hidden" id="insertFlag" value="0" />
                                <form id="form" action="./">
                                <table style="border-spacing: 10px; border-collapse: separate; direction: rtl">
                                    <tr id="trcode">
                                        <td id="tagPropId">קוד סניף:</td>
                                        <td>
                                            <input id="PropId" class="input" type="text" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td id="tagPropName">שם סניף:</td>
                                        <td>
                                            <input id="PropName" class="input" type="text" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td style="padding-top: 10px;">
                                            <input style="margin-right: 5px;" type="button" id="Save" value="עדכון" />
                                            <input id="Cancel" type="button" value="ביטול" />
                                        </td>
                                    </tr>
                                </table>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    app_menu.activeLayoutMenu("liEntity");
    app_menu.breadcrumbs("Main", "DefEntity", 'en');
</script>

Pro.Mvc/Views/Common/Final.cshtml
@model Pro.Mvc.Models.ResultModel
@{
    Layout = "~/Views/Shared/_ViewCo.cshtml";
    ViewBag.Title = "Result";
    
    string Title = Model.Title;
    string Message = Model.Message;
}


<div class="global" style="text-align: center">
    <div class="center-box">
        <div class="container">
            <img src="~/Images/ok-alert.png" alt="Ok" />
            <h4>@Title</h4>
            <p style="text-align:center; direction:rtl; font-family:Arial; font-size:16px;border:none; overflow:hidden">
                @Message
                <br />
                <a href="~/home/Main">לדף הראשי</a>
            </p>
        </div>


        <div class="footer">
            
        </div>

    </div>
</div>

Pro.Mvc/Views/Common/_BatchMessageView.cshtml
@model Pro.Data.Entities.SendMessageView
@{
    Layout = "~/Views/Shared/_ViewIframe.cshtml";
    
   
}

@section head {

    @Scripts.Render("~/bundles/jqx")
    <link rel="stylesheet" href="~/Scripts/app/app-form.css" type="text/css" />
    <style type="text/css">
        #cmsBody{
            direction:rtl;
            width:90%;
            margin:10px;
        }
    </style>
}

@section scripts {
    <script type="text/javascript">

    $(document).ready(function () {

    });
 
</script>
}

<div id="cmsBody">
    @Html.Raw(Model.View)
</div>

<!--end of content-wrapper-->

Pro.Mvc/Views/Common/_MemberCategories.cshtml
@{

    ViewBag.Title = "Members";
    Layout = "~/Views/Shared/_ViewIframe.cshtml";
    int rcdid = Nistec.Types.ToInt(Request.QueryString["id"]);
 
}

@section head {

    @Scripts.Render("~/bundles/jqx")
    <link rel="stylesheet" href="~/Scripts/app/app-form.css" type="text/css" />
}

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            
            var rcdid = '@rcdid';
            $('#MemberRecord').val(rcdid);

            var dataSource =
               {
                   dataType: "json",
                   dataFields: [
                       { name: 'PropId' },
                       { name: 'PropName' }
                   ],
                   type: 'POST',
                   url: '@Url.Action("GetCategoriesView", "Common")'
               };

            var dataAdapter = new $.jqx.dataAdapter(dataSource, {
                async: false,
                //contentType: "application/json; charset=utf-8",
                loadError: function (jqXHR, status, error) {
                    //alert("categoriesAdapter failed: " + error);
                },
                loadComplete: function (data) {
                    //alert("categoriesAdapter is Loaded");
                }
            });
            //categoriesAdapter.dataBind();


            $("#CategoriesType").jqxListBox(
            {
                rtl: true,
                source: dataAdapter,
                width: 500,
                height: 210,
                multiple: true,
                checkboxes: true,
                displayMember: 'PropName',
                valueMember: 'PropId'
            });
            $('#CategoriesType').on('checkChange', function (event) {
                app_jqxcombos.listCheckBoxToInput("CategoriesType", "Categories");
            });

            var view_source =
                {
                    datatype: "json",
                    datafields: [
                            { name: 'PropId', type: 'number' },
                            { name: 'MemberRecord', type: 'number' }
                    ],
                    id: 'MemberId',
                    data: { 'rcdid': '@rcdid'},
                    type: 'POST',
                    url: '@Url.Action("GetMemberCategories", "Co")'
                };

                var srcMemberType;

                var viewAdapter = new $.jqx.dataAdapter(view_source, {
                    async: false,
                    loadComplete: function (records) {
                        if (records) {

                            var categoriesType = app_jqxcombos.getDataCheckedList(records, "PropId");
                            app_jqxcombos.selectCheckList("CategoriesType", categoriesType);
                            $("#categoriesHeader").append("<h4>הגדרת סיווג</h4>");

                        }
                    },
                    loadError: function (jqXHR, status, error) {
                       app_dialog.alert('Error: ' + error);
                    },
                    beforeLoadComplete: function (records) {
                    }
                });
                viewAdapter.dataBind();
            //}


            //categories dialog

                $('#categoriesSubmit').on('click', function (e) {
                    $.ajax({
                        url: '@Url.Action("UpdateMemberCategories", "Co")',
                        type: 'post',
                        dataType: 'json',
                        data: $('#categoriesForm').serialize(),
                        success: function (data) {
                           app_dialog.alert(data.Message);
                            if (data.Status >= 0) {
                                var rcdid = $('#MemberRecord').val();
                                window.parent.triggerCategoriesComplete(rcdid);
                                $('#categoriesForm')[0].reset();
                                $('#MemberRecord').val(rcdid);
                            }
                        },
                        error: function (jqXHR, status, error) {
                           app_dialog.alert(error);
                        }
                    });
                });

            $('#categoriesCancel').on('click', function (e) {
                var rcdid = $('#MemberRecord').val();
                $('#categoriesForm')[0].reset();
                $('#categoriesForm').jqxValidator('hide');
                $('#MemberRecord').val(rcdid);

            });
        });

    </script>
}

<div style="margin: 0px;">

    <div id="jqxWidget" style="margin: 0 auto; display: block; direction: rtl">
        <div id="categoriesWindow">
            <div id="categoriesHeader">
            </div>
            <div id="categoriesBody">
                <form class="categoriesForm" id="categoriesForm" method="post" action="/Co/UpdateMemberCategories">
                    <input type="hidden" id="Categories" name="Categories" />
                    <div style="direction: rtl; text-align: right">
                        <div class="form-group">
                            <label class="column">
                                ת.ז :</label>
                            <input id="MemberRecord" name="MemberRecord" readonly="true" type="text" class="text-mid" />
                        </div>
                             <div class="form-group">
                                <label class="column">
                                    קבוצות סיווג:</label>
                                <div id="CategoriesType" name="CategoriesType" style="padding: 0px" data-type="checklist">
                                </div>
                            </div>
                        <div style="height: 5px"></div>
                        <div>
                            <input id="categoriesSubmit" class="btn-default btn7" type="button" value="עדכון" />
                            <input id="categoriesCancel" class="btn-default btn7" type="button" value="ביטול" />
                            <!--<input class="btn-default btn2" type="button" value="הוספת אנשי קשר" />-->
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>
<!--end of content-wrapper-->

Pro.Mvc/Views/Common/_Prompt.cshtml
@model Pro.Mvc.Models.ResultModel
@{

    string Title = Model.Title;
    string Message = Model.Message;
}
    <script src="~/Scripts/jq/jquery.min.js"></script>

<div style="text-align:center; direction:rtl; font-family:Arial; font-size:16px">
    <h4>@Title</h4>
    <textarea readonly="readonly" rows="4" cols="40" style="text-align:center; direction:rtl; font-family:Arial; font-size:16px;border:none; overflow:hidden">
     @Message
    </textarea>
    <div id="promptNext"></div>
</div>
<script type="text/javascript">

    doPromptNext();
    function doPromptNext() {
        var status = '@Model.Status';
        if (status == 1) {
            $('#promptNext').append('<input type="button" id="btnTrigger" value="המשך"/>');
            setTimeout(function () {
                window.parent.trigger_Prompt(status);
            }, 1000);
        }
    };

    $(document).ready(function () {
        $('#btnTrigger').click(function () {
            window.parent.trigger_Prompt(1);
        });
    });
</script>

Pro.Mvc/Views/Common/_Targets.cshtml
@{
    Layout = "~/Views/Shared/_ViewIframe.cshtml";
    ViewBag.Title = "Members";
    var mode=Request["mode"];
    var cat = Request["cat"];
}
@section head { 

    @Scripts.Render("~/bundles/jqx")
    @Scripts.Render("~/bundles/jqxgrid")
    <script type="text/javascript" src="~/jqwidgets/jqxdata.export.js"></script>
    <script type="text/javascript" src="~/jqwidgets/jqxgrid.export.js"></script> 

    <style type="text/css">
        input {
            direction:rtl;text-align:right;
        }
    </style>

}


@section scripts {

    <script type="text/javascript">
        $(document).ready(function () {
            JSON.useDateParser();
            var theme = 'Arctic';
            // prepare the data

            var source =
            {
                datatype: "json",
                datafields: [
                    { name: 'Id', type: 'number' },
                    { name: 'Target', type: 'string' },
                    { name: 'Personal', type: 'string' },
                    //{ name: 'Creation', type: 'date' },
                    { name: 'AccountId', type: 'number' }
                   // { name: 'UserId', type: 'number' }
                    
                ],
                id: 'Id',
                type:'POST',
                url: '@Url.Action("GetTargets", "Common")',
                data:{'mode':'@mode','cat':'@cat'},
                //pagenum: 3,
                pagesize: 12,
                root: 'Rows',
                beforeprocessing: function (data) {
                    source.totalrecords = data.TotalRows;
                },
                pager: function (pagenum, pagesize, oldpagenum) {
                    // callback called when a page or page size is changed.
                },
                sort: function () {
                    // update the grid and send a request to the server.
                    $("#jqxgrid").jqxGrid('updatebounddata', 'sort');
                },
                filter: function () {
                    $("#jqxgrid").jqxGrid('updatebounddata', 'filter');
                }
            };
            var dataAdapter = new $.jqx.dataAdapter(source, {
                async:false,
                loadComplete: function (data) { },
                loadError: function (xhr, status, error) { alert(' status: ' + status + '\n error ' + error) }
            });
        
            // create Tree Grid
            $("#jqxgrid").jqxGrid(
            {
                width: '100%',
                //height:'500',
                autoheight: true,
                rtl: true,
                source: dataAdapter,
                localization: getLocalization('he'),
                virtualmode: true,
                rendergridrows: function (obj) {
                    return obj.data;
                },
                pageable: true,
                pagermode: 'simple',
                sortable: true,
                showfilterrow: true,
                filterable: true,
                columns: [
                  { text: 'מזהה', dataField: 'Id', filterable: false, width: 100, cellsalign: 'right', align: 'center' },
                  { text: 'נמען', dataField: 'Target', filtercondition: 'CONTAINS',  cellsalign: 'right', align: 'center' },
                  { text: 'פרטים', dataField: 'Personal', filtercondition: 'CONTAINS', cellsalign: 'right', align: 'center' }
                  //{ text: 'משתמש', dataField: 'UserId', filterable: false, width: 80, cellsalign: 'right', align: 'center' },
                  //{ text: 'נוצר', type: 'date', dataField: 'Creation', filterable: false, width: 120, cellsformat: 'd', cellsalign: 'right', align: 'center' }
                ]
            });
            //$('#btnclearfilter').jqxButton({ width: '120', height: '30' });
            $('#btnclearfilter').click(function () {
                $("#jqxgrid").jqxGrid('clearfilters');
            });

            //$("#excelExport").jqxButton();
            //$("#csvExport").jqxButton();
            //$("#excelExport").click(function () {
            //    alert('excelExport');
            //    exportToCsv();
            //    //$("#jqxgrid").jqxGrid('exportdata', 'xls', 'jqxGrid');
            //});
            

        });

        
    </script>
}


@section featured {


}

<div class="clear"></div>

<div class="global">
    <div class="container">
        @*<h4 class="rightPan">רשימת נמענים לדיוור.</h4>*@
        <div class="grid-wrap">
            <div style="display: inline; float: right">
              
            </div>

            <div id="jqxWidget">
                <div id="jqxgrid" style="position:relative;z-index:1;"></div>
                <input style="margin-top: 10px;" value="הסר סינון" id="btnclearfilter" type="button" />
            </div>
        </div>
    </div>
</div>